### ISSUE TITLE
Add Coverage analysis to Codacy

### ISSUE THREAD

**Issue by mcgivrer** [mcgivrer/basic-game-framework#48]
Add travis steps see https://github.com/codacy/codacy-coverage-reporter#travis-ci 

Edit the travis.yml file:

```yml
before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets[0].browser_download_url')

after_success:
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
```
